# Generated by Django 6.0.3 on 2026-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_userprofile_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
