# Generated by Django 6.0.3 on 2026-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_userprofile_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diethabit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
