# Generated by Django 6.0.3 on 2026-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='report_image',
            field=models.FileField(upload_to='patient_reports/'),
        ),
    ]
